apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.configmap.labels.app }}
data:
  NEXT_HOST: {{ .Values.configmap.data.NEXT_HOST | quote }}