apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.hpa.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.hpa.labels.app }}
spec:
  scaleTargetRef:
    kind: "Deployment"
    name: {{ .Values.deployment.name }}
    apiVersion: "apps/v1"
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  - type: "Resource"
    resource:
      name: "cpu"
      targetAverageUtilization: {{ .Values.hpa.cpuTargetAverageUtilization }}