apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.service.labels.app }}
spec:
  ports:
  - protocol: "TCP"
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Values.deployment.labels.app }}
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP | quote }}